Below is a checklist of tasks to complete for finalizing the PUMP project. For each, we can list champion & target date for completion. 

This list is not complete - to be added to and checked off by everyone.

# R package
- Expand models (e.g. D3 designs with ICC non zero, and others discussed) & validate (Kristen, TBD)
    Done this (in particular the ICC stuff) except for additional models, to be postponed.
    TO DO: Add the d1.1_mcc model (simple randomization)
    Done!
- Run additional validation for extreme values (Kristen, TBD)
    Done.
- Update with new naming convention (Kristen)
    Done!
- Complete code commenting (Kristen, TBD)
    Done enough.
- Complete all testing (Kristen and Luke, TBD)
    Done enough, will add tests as issues arise.
- Source code completed, ASCII files, with formatted help files and be packaged for easy installation. 
    Still to do.
- Submit package to CRAN - including JSS submission as vignettes in the package. 
- Make sure all functions still work when specifying one outcome (Kristen)
     Done  
- Issue: when estimating lower-level sample sizes, it's possible for range of sample sizes to produce same power. Kristen refining returned objected to contain information of issue. Luke refining diagnostic plot. Kristenn working with Zarni to return note in Shiny, along with revised version of info in vignette. 
- Luke has added return of all call parameters. Refining formatting. 
- Vignettes expanding to demonstrate functionality. 
- Add functions for expanded designs with same power - e.g. need to add d3.2_m3fc2rc - same power as d3.2_m3ff2rc
- Change d1.1_m2cc to d1.1_m1c (and Kristen will check first)
- Kristin will send nots about credit - including ies grant number.

## Kristen's todo list
- once sample size code is stable, rerun all validation
- understand unit test with correlated outcomes
- add flag for flat power curve to help with shiny app, work with Zarni to incorporate help procedure
- implement d3.2_m2fc2rc, update d1.1_m2cc to d1.1_m1c
- remove just_results_table_flag
- hash out power definitions: unadjusted p-values for complete power, whether or not to include zero outcomes for min power, complete power
- recruit Jonathan S for testing
- update sample size vignette

# Shiny app
- Aim to have draft to share in next meeting
- Talk to Zarni about ability to do simple git pulls for updates

# User testing
- Luke and Kristen have some possible test users to reach out to
- Not concerned with much testing of package.

# Manuscript
- presubmission inquiry: abstract and introduction plus outline/structure - TBD whether we do it.
- draft on 11/31 that feels close to final - then think about presubmission inquiry.
- Luke finishing vignette and plugging in.
- Kristen H to do first draft of conclusion.
- Kristin P will write abstract.

# Video
- Reach out to video staff with plans and questions (Zarni, 7/31)
- Budget video (Kristin, 8/15)

# Presentation
- Success! Kristin P has saved the slides for attaching to our final performance report. 

# Next check-in

# Stretch goals
- Potentially use simulations to estimate rho matrix for users when entering other information about data - corr between outcomes, R2's (Kristen, maybe, TBD)
- tool that helps user build a block matrix of correlations based on a list of correlations between outcomes
- tool the helps user determine correlation between test statistics using simulation
- resolve terminology: MDES, ES, ATE_ES, impact?
- additional designs, including: d3.3_2mff, d3.1_m3fc2rr, d2.2_m2cc with cluster robust standard errors
- for sample size, allow a vector of MDES, i.e. combination of zero and nonzero values, and allow for numZero flag
- effect size calculator
- speed up everything
- WY follow up: WY with a small number of schools, large number of permutations, and no effect, do we get the intended power/p-value?  What if we don’t do any adjustment–is it because of divergent/unstable models?

