---
title: "Validate Power: Westfall-Young"
author: "Kristin Porter, Zarni Htet, Kristen Hunter"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output:
  html_document:
    df_print: paged
    fig_caption: yes
    fig_height: 8
    fig_width: 10
    highlight: monochrome
    theme: spacelab
    toc: yes
    toc_depth: 5
    toc_float: yes
  github_document:
    df_print: paged
    fig_caption: yes
    fig_height: 8
    fig_width: 10
    toc: yes
---

```{r knit.options, echo = FALSE}
# by default, all code chunks will cache their results
knitr::opts_chunk$set(cache = FALSE, warning = FALSE, message = FALSE, echo = FALSE)
```

```{r setup}
library(here)
library(pander)    # For good table format

# default tables to round to 3 digits
panderOptions('round', 3)

# simulation and user parameters
source(here::here("Validation/Simulations", "params.R"))
user.params.default <- user.params.list
sim.params.list[['procs']] <- c("Bonferroni", "BH", "Holm", "WY-SS", "WY-SD")
sim.params.list[['S']] <- 1000
sim.params.list[['Q']] <- 1
sim.params.list[['B']] <- 1000

sim.params.default <- sim.params.list
```

```{r blocked.2}
user.params.list <- user.params.default
user.params.list[['nbar']] <- 50
user.params.list[['K']] <- 1
user.params.list[['ICC.3']] <- NULL
user.params.list[['omega.3']] <- NULL
user.params.list[['R2.3']] <- NULL
user.params.list[['nbar']] <- 50
```

# Blocked 2 level models

Constant effects

```{r blocked.2c}
design <- "blocked_i1_2c"
user.params.list[['omega.2']] <- 0
user.params.list[['ICC.2']] <- rep(0, M)
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_2c_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_2c_power_plot)
```

Fixed effects

```{r blocked.2f}
design <- "blocked_i1_2f"
user.params.list[['omega.2']] <- user.params.default[['omega.2']]
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_2f_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_2f_power_plot)
```

Random effects

```{r blocked.2r}
design <- "blocked_i1_2r"
user.params.list[['ICC.2']] <- user.params.default[['ICC.2']]
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_2r_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_2r_power_plot)
```

```{r rho0}
rho.default <- 0
default.rho.matrix <- gen_corr_matrix(M = M, rho.scalar = rho.default)
user.params.list[['rho.default']] <- rho.default
user.params.list[['rho.X']] <- user.params.list[['rho.C']] <- default.rho.matrix
user.params.list[['rho.u0']] <- user.params.list[['rho.u1']] <- user.params.list[['rho.r']] <- default.rho.matrix
```

Constant effects, $\rho = 0$

```{r blocked.2c.rho0}
design <- "blocked_i1_2c"
user.params.list[['omega.2']] <- 0
user.params.list[['ICC.2']] <- rep(0, M)
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_2c_rho0_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_2c_rho0_power_plot)
```

Fixed effects, $\rho = 0$

```{r blocked.2f.rho0}
design <- "blocked_i1_2f"
user.params.list[['omega.2']] <- user.params.default[['omega.2']]
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_2f_rho0_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_2f_rho0_power_plot)
```

Random effects, $\rho = 0$

```{r blocked.2r.rho0}
design <- "blocked_i1_2r"
user.params.list[['ICC.2']] <- user.params.default[['ICC.2']]
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_2r_rho0_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_2r_rho0_power_plot)
```



```{r rho.reset}
rho.default <- user.params.default[['rho.default']]
user.params.list[['rho.default']] <- rho.default
default.rho.matrix <- gen_corr_matrix(M = M, rho.scalar = rho.default)
user.params.list[['rho.X']] <- user.params.list[['rho.C']] <- default.rho.matrix
user.params.list[['rho.u0']] <- user.params.list[['rho.u1']] <- user.params.list[['rho.r']] <- default.rho.matrix
```

# Cluster 2 level

```{r cluster.2c}
user.params.list <- user.params.default
user.params.list[['nbar']] <- 50

user.params.list[['K']] <- 1
user.params.list[['ICC.3']] <- NULL
user.params.list[['omega.3']] <- NULL
user.params.list[['R2.3']] <- NULL
user.params.list[['omega.2']] <- 0

# params to help have a decent power
user.params.list[['ICC.2']] <- rep(0.1, M)
user.params.list[['J']] <- 60
user.params.list[['ATE_ES']] <- rep(0.25, M)
  
design <- "simple_c2_2r"
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
simple_c2_2r_power_plot <- gen.power.results.plot(params.file.base, design)
print(simple_c2_2r_power_plot)
```

# Blocked 3 level

```{r blocked.3r}
user.params.list <- user.params.default

# for a reasonable runtime
user.params.list[['J']] <- 10
user.params.list[['K']] <- 5
user.params.list[['nbar']] <- 20
sim.params.list[['B']] <- 200
user.params.list[['S']] <- 20

design <- "blocked_i1_3r"
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_i1_3r_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_i1_3r_power_plot)
```

# Cluster 3 level

```{r cluster.3r}
user.params.list <- user.params.default
user.params.list[['nbar']] <- 50

# assumptions
user.params.list[['omega.2']] <- 0
user.params.list[['omega.3']] <- 0

# for a reasonable runtime and power
user.params.list[['J']] <- 10
user.params.list[['K']] <- 5
user.params.list[['nbar']] <- 20
user.params.list[['ATE_ES']] <- rep(1, M)
user.params.list[['ICC.3']] <- rep(0.1, M)
user.params.list[['ICC.2']] <- rep(0.1, M)

design <- "simple_c3_3r"
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
simple_c3_3r_power_plot <- gen.power.results.plot(params.file.base, design)
print(simple_c3_3r_power_plot)
```

# Blocked cluster

```{r blocked.cluster}
user.params.list <- user.params.default

user.params.list[['omega.2']] <- 0

# for a reasonable runtime and power
# user.params.list[['J']] <- 10
# user.params.list[['K']] <- 5
# user.params.list[['nbar']] <- 20
# user.params.list[['ATE_ES']] <- rep(0.25, M)
# user.params.list[['ICC.3']] <- rep(0.1, M)
# user.params.list[['ICC.2']] <- rep(0.1, M)
```

Blocked cluster, fixed effects

```{r blocked.cluster.3f}
design <- "blocked_c2_3f"
user.params.list[['R2.3']] <- rep(0, M)
user.params.list[['ICC.3']] <- rep(0, M)
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_c2_3f_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_c2_3f_power_plot)
```

Blocked cluster, random effects

```{r blocked.cluster.3r}
design <- "blocked_c2_3r"
user.params.list[['R2.3']] <- user.params.default[['R2.3']]
user.params.list[['ICC.3']] <- user.params.default[['ICC.3']]
params.file.base <- gen_params_file_base(user.params.list, sim.params.list, design)
blocked_c2_3r_power_plot <- gen.power.results.plot(params.file.base, design)
print(blocked_c2_3r_power_plot)
```

