---
title: "Validate_power_mdes_sample_blocked_i1_2c"
author: "Kristin Porter & Zarni Htet"
output: github_document
---

### Libraries and Source Files

```{r libaries, warnings = FALSE, message = FALSE}
library(RcppEigen) # Linear algebra calculations
library(snow)      # Parallelization and use of multiple clusters 
library(lme4)      # Linear mixed effect models
library(PowerUpR)  # Comparison with another package that has some limitations
library(multtest)  # Multiple Testing Procedures package
library(tictoc)    # For timing of the scripts
library(here)      # For relative path sourcing
```

```{r sourcefiles}
source(here::here("Validation/Simulations", "adjust.WY.R")) # MTP Westfall-Young
source(here::here("Validation/Simulations", "gen_data_dist_2_levels.R")) # data generating functions for 2 level block and cluster
source(here::here("Validation/Simulations", "power_mcs_2_levels.R")) # Estimate power for each of the designs by running data generating function S sample times and fitting models to estimate power.
source(here::here("Validation/Simulations", "validate_power_mdes_sample_blocked_i1_2c.R")) # 
```


### Parameters for Monte Carlo Simulation Runs

#### Validating

```{r validation_parameter_specifications}
rho <- c(0,0.2,0.5,0.8)
ncl <-8 #done
procs <- c("Bonferroni", "BH", "Holm","WY") #done
design <- c("Blocked_i1_2c", "Blocked_i1_2f", "Blocked_i1_2r") #done
M <- 2 #done
MDES <- rep(0.125, M) #done
p.j.range <- c(0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5,0.5) #done
p.j <- 0.5 #done
S = 2000 #done
B = 10000 #done
J = 20 # done
n.j = 100 #done
theta <- matrix(0,M,M) #done 
diag(theta) <- 0 # done
omega <- rep(0,M) #done
Gamma.00 <- rep(0,M) #done
sig.sq <- rep(1,M)
alpha <- 0.05 #done
ICC <- rep(0, M) #done
R2.2 <- rep(0,M) #done 
R2.1 <- rep(0, M) #done
maxT <- FALSE #done
rho.0_lev1<-matrix(rho,M,M); diag(rho.0_lev1) <- 1 #done
rho.0_lev2<-matrix(rho,M,M); diag(rho.0_lev2) <- 1 #done
rho.1_lev2<-matrix(rho,M,M); diag(rho.1_lev2) <- 1 #done
check <- TRUE #done
```

### Firing Up & Storing Results from Monte Carlo Simulation Runs

```{r}
tic()
validate_power_blocked_i1_2c(rho = rho, ncl = ncl, procs = procs, design = design, M = M, MDES = MDES,
                             p.j.range = p.j.range, p.j = p.j, S = S, B = B, J = J, 
                             n.j = n.j, theta = theta, omega = omega, Gamma.00 = Gamma.00, sig.sq = sig.sq,
                             alpha = alpha, ICC = ICC, R2.2 = R2.2, R2.1 = R2.1, maxT = maxT, rho.0_lev1 = rho.0_lev1,
                             rho.0_lev2 = rho.0_lev2, rho.1_lev2 = rho.1_lev2, check = check)
toc()     
```

### Firing up & Storing Results from derived function

```{r}

```

### Comparing results for validation

```{r}

```




