---
title: "Validation_Level2_RCT_001"
author: "Kristin Porter & Zarni Htet"
output: github_document
---

### Libraries and Source Files

```{r libaries, warnings = FALSE, message = FALSE}
library(RcppEigen) # Linear algebra calculations
library(snow)      # Parallelization and use of multiple clusters 
library(lme4)      # Linear mixed effect models
library(PowerUpR)  # Comparison with another package that has some limitations
library(multtest)  # Multiple Testing Procedures package
library(tictoc)    # For timing of the scripts
library(here)      # For relative path sourcing
```

```{r sourcefiles}
source(here::here("Validation/Simulations", "adjust.WY.R")) # MTP Westfall-Young
source(here::here("Validation/Simulations", "gen_data_dist_2_levels.R")) # data generating functions for 2 level block and cluster
source(here::here("Validation/Simulations", "power_mcs_2_levels.R")) # Estimate power for each of the designs by running data generating function S sample times and fitting models to estimate power.
```


### Parameters for Monte Carlo Simulation Runs

#### Validating

* rho
* ncl
* procs
* design
* M
* MDES
* p.j.range
* S
* B
* J
* n.j
* theta
* omega
* Gamma
* sig.sq
* alpha
* ICC
* R2.2
* R2.1

```{r validation_parameter_specifications}

rho <- c(0,0.2,0.5,0.8)
ncl <-8
procs <- c("Bonferroni", "BH", "Holm","WY") 
design <- c("Blocked_i1_2c", "Blocked_i1_2f", "Blocked_i1_2r")
M <- 2
MDES <- rep(0.125, M)
p.j.range <- c(0.5,0.5)
S = 2000
B = 10000
J = 20
n.j = 100
theta <- matrix(0,M,M) 
diag(theta) <- 0 
omega <- rep(0,M)
Gamma.00 <- rep(0,M)
sig.sq <- rep(1,M)
alpha <- 0.05
ICC <- rep(0, M) 
R2.2 <- rep(0,M) 
R2.1 <- rep(0, M)
```



### Firing Up & Storing Results from Monte Carlo Simulation Runs

```{r}

```

### Firing up & Storing Results from derived function

```{r}

```

### Comparing results for validation

```{r}

```




