---
title: "Validate Power: MDES and SS power definitions"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---


```{r knit.options, echo = FALSE}
# by default, all code chunks will cache their results
knitr::opts_chunk$set(
  cache = FALSE, warning = FALSE, message = FALSE, echo = FALSE,
  fig.height = 7
)
```

```{r setup}
library(here)
library(PUMP)
library(pander)
# default tables to round to 3 digits
panderOptions('round', 3)
source(here::here("validation/code", "misc.R"))
```

```{r sim.params}
sim.params.list <- list(
  S = 5000                     # Number of samples for Monte Carlo Simulation
  , Q = 1
)
```

```{r}
M <- 3
model.params.list <- list(
  M = 3                                   # number of outcomes
  , J = 30                                # number of schools
  , K = 10                                # number of districts (for two-level model, set K = 1)
  , nbar = 50                             # number of individuals per school
  , rho.default = 0.5                     # default rho value
  ################################################## grand mean outcome and impact
  , MDES = rep(0.125, M)                  # minimum detectable effect size      
  ################################################## level 3: districts
  , numCovar.3 = 1                        # number of district covariates
  , R2.3 = rep(0.1, M)                    # percent of district variation explained by district covariates
  , ICC.3 = rep(0.2, M)                   # district intraclass correlation
  ################################################## level 2: schools
  , numCovar.2 = 1                        # number of school covariates
  , R2.2 = rep(0.1, M)                    # percent of school variation explained by school covariates
  , ICC.2 = rep(0.2, M)                   # school intraclass correlation	
  , omega.2 = rep(0.1, M)                 # ratio of school effect size variability to random effects 
  ################################################## level 1: individuals
  , numCovar.1 = 1                        # number of individual covariates
  , R2.1 = rep(0.1, M)                    # percent of indiv variation explained by indiv covariates
)
params.default <- model.params.list
d_m <- "d3.2_m3ff2rc"
```

# Power Validation

```{r raw_D1indiv}
d_m <- "d3.2_m3ff2rc"
model.params.list$MDES <- rep(0.1, 3)
model.params.list$J <- 3
model.params.list$K <- 22
model.params.list$nbar <- 150
model.params.list$R2.1 <- rep(0.1, M)
model.params.list$R2.2 <- rep(0.7, M)
model.params.list$R2.3 <- NULL
model.params.list$ICC.2 <- rep(0.05, M)
model.params.list$ICC.3 <- rep(0.4, M)
model.params.list$rho <- 0.4
d3.2_m3ff2rc_rawD1indiv_power_plot <- gen.power.results.plot(gen_params_file_base(model.params.list, sim.params.list, d_m), d_m)
print(d3.2_m3ff2rc_rawD1indiv_power_plot)
```

```{r bonf_D1indiv}
d_m <- "d3.2_m3ff2rc"
model.params.list$MDES <- rep(0.1, 3)
model.params.list$J <- 4
model.params.list$K <- 17
model.params.list$nbar <- 160
model.params.list$R2.1 <- rep(0.3, M)
model.params.list$R2.2 <- rep(0.75, M)
model.params.list$R2.3 <- NULL
model.params.list$ICC.2 <- rep(0.05, M)
model.params.list$ICC.3 <- rep(0.4, M)
model.params.list$rho <- 0.4
d3.2_m3ff2rc_bonfD1indiv_power_plot <- gen.power.results.plot(gen_params_file_base(model.params.list, sim.params.list, d_m), d_m)
print(d3.2_m3ff2rc_bonfD1indiv_power_plot)
```

```{r bonf_min1}
d_m <- "d3.2_m3ff2rc"
model.params.list$MDES <- rep(0.1, 3)
model.params.list$J <- 4
model.params.list$K <- 16
model.params.list$nbar <- 150
model.params.list$R2.1 <- rep(0.25, M)
model.params.list$R2.2 <- rep(0.75, M)
model.params.list$R2.3 <- NULL
model.params.list$ICC.2 <- rep(0.05, M)
model.params.list$ICC.3 <- rep(0.4, M)
model.params.list$rho <- 0.4
d3.2_m3ff2rc_bonfmin1_power_plot <- gen.power.results.plot(gen_params_file_base(model.params.list, sim.params.list, d_m), d_m)
print(d3.2_m3ff2rc_bonfmin1_power_plot)
```

```{r bonf_complete}
d_m <- "d3.2_m3ff2rc"
model.params.list$MDES <- rep(0.1, 3)
model.params.list$J <- 4
model.params.list$K <- 16
model.params.list$nbar <- 150
model.params.list$R2.1 <- rep(0.25, M)
model.params.list$R2.2 <- rep(0.75, M)
model.params.list$R2.3 <- NULL
model.params.list$ICC.2 <- rep(0.05, M)
model.params.list$ICC.3 <- rep(0.4, M)
model.params.list$rho <- 0.4
d3.2_m3ff2rc_bonfcomplete_power_plot <- gen.power.results.plot(gen_params_file_base(model.params.list, sim.params.list, d_m), d_m)
print(d3.2_m3ff2rc_bonfcomplete_power_plot)
```

# MDES

```{r}
model.params.list <- params.default

# assumptions
model.params.list[['omega.2']] <- NULL
model.params.list[['omega.3']] <- NULL

# param settings to have a decent level of power
model.params.list[['J']] <- 40
model.params.list[['K']] <- 20
model.params.list[['MDES']] <- rep(0.25, M)
model.params.list[['ICC.3']] <- rep(0.1, M)
model.params.list[['ICC.2']] <- rep(0.1, M)
```

```{r mdes_D1indiv}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_D1indiv')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_D1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_D1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r mdes_min1}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r mdes_min2}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_min2_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_min2_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r mdes_complete}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

# Sample Size

## Sample Size J

```{r ss_D1indiv_J}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_D1indiv')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_D1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_D1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_min1_J}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_min2_J}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_min2_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_min2_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_complete_J}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

## Sample Size K

```{r ss_D1indiv_K}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_K_D1indiv')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_K_D1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_K_D1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_min1_K}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_K_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_K_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_K_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_min2_K}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_K_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_K_min2_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_K_min2_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_complete_K}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_K_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_K_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_K_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

## Sample Size nbar

```{r ss_D1indiv_nbar}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_nbar_D1indiv')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_nbar_D1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_nbar_D1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_min1_nbar}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_nbar_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_nbar_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_nbar_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_min2_nbar}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_nbar_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_nbar_min2_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_nbar_min2_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r ss_complete_nbar}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_nbar_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_nbar_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_nbar_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


# Changing correlation

## correlation = 0

```{r rho0}
model.params.list[['rho']] <- 0
```

```{r mdes_min1_rho0}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r mdes_complete_rho0}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


```{r ss_min1_J_rho0}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


```{r ss_complete_J_rho0}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

## correlation = 0.8

```{r rho08}
model.params.list[['rho']] <- 0.8
```

```{r mdes_min1_rho08}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r mdes_complete_rho08}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


```{r ss_min1_J_rho08}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


```{r ss_complete_J_rho08}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


## correlation = 1

```{r rho1}
model.params.list[['rho']] <- 1
```

```{r mdes_min1_rho1}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```

```{r mdes_complete_rho1}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'mdes_complete')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_mdes_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_mdes_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


```{r ss_min1_J_rho1}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min1')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_min1_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_min1_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


```{r ss_complete_J_rho1}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
sample.file <- find_file(params.file.base, type = 'sample_J_min2')
if(length(sample.file) == 0)
{
  warning(paste('Results not yet computed for given parameters:', params.file.base))
} else
{
  d3.3_m3rc2rc_sample_J_complete_results <- readRDS(sample.file)
  pander::pandoc.table(
    d3.3_m3rc2rc_sample_J_complete_results,
    style = "grid", split.tables = 100, row.names = FALSE,
    caption = d_m
  )
}
```


