---
title: "Validate Power: Westfall-Young"
date: "`r format(Sys.Date(), '%B %d, %Y')`"
output: pdf_document
---

```{r knit.options, echo = FALSE}
knitr::opts_chunk$set(
  cache = FALSE, warning = FALSE, message = FALSE, echo = FALSE,
  fig.height = 6.5
)
```

```{r setup}
library(here)
library(PUMP)
library(pander)
# default tables to round to 3 digits
panderOptions('round', 3)
source(here::here("validation/code", "misc.R"))
```

```{r sim.params}
sim.params.list <- list(
  S = 2000                     # Number of samples for Monte Carlo Simulation
  , Q = 1
  , B = 1000
  , MTP = c("Bonferroni", "BH", "Holm", "WY-SS")
)
sim.params.default <- sim.params.list
```

```{r model.params}
M <- 3
model.params.list <- list(
  M = 3                                   # number of outcomes
  , J = 30                                # number of schools
  , K = 10                                # number of districts (for two-level model, set K = 1)
  , nbar = 50                             # number of individuals per school
  , rho.default = 0.5                     # default rho value
  # , S.id = NULL                         # N-length vector of indiv school assignments (optional)
  # , D.id = NULL                         # N-length vector of indiv district assignments (optional)
  ################################################## grand mean outcome and impact
  # , Xi0 = 0                             # scalar grand mean outcome under no treatment
  , MDES = rep(0.125, M)                  # minimum detectable effect size      
  ################################################## level 3: districts
  , numCovar.3 = 1                        # number of district covariates
  , R2.3 = rep(0.1, M)                    # percent of district variation explained by district covariates
  # , rho.V = default.rho.matrix          # MxM correlation matrix of district covariates
  , ICC.3 = rep(0.2, M)                   # district intraclass correlation
  , omega.3 = rep(0.1, M)                 # ratio of district effect size variability to random effects variability
  # , rho.w0 = default.rho.matrix         # MxM matrix of correlations for district random effects
  # , rho.w1 = default.rho.matrix         # MxM matrix of correlations for district impacts
  , kappa.w = matrix(0, M, M)             # MxM matrix of correlations between district random effects and impacts
  ################################################## level 2: schools
  , numCovar.2 = 1                        # number of school covariates
  , R2.2 = rep(0.1, M)                    # percent of school variation explained by school covariates
  # , rho.X = default.rho.matrix          # MxM correlation matrix of school covariates
  , ICC.2 = rep(0.2, M)                   # school intraclass correlation	
  , omega.2 = rep(0.1, M)                 # ratio of school effect size variability to random effects variability
  # , rho.u0 = default.rho.matrix         # MxM matrix of correlations for school random effects
  # , rho.u1 = default.rho.matrix         # MxM matrix of correlations for school impacts
  , kappa.u = matrix(0, M, M)             # MxM matrix of correlations between school random effects and impacts
  ################################################## level 1: individuals
  , numCovar.1 = 1                        # number of individual covariates
  , R2.1 = rep(0.1, M)                    # percent of indiv variation explained by indiv covariates
  # , rho.C = default.rho.matrix          # MxM correlation matrix of individual covariates
  # , rho.r = default.rho.matrix          # MxM matrix of correlations for individual residuals 
)
model.params.default <- model.params.list
```

# d2.1 models

```{r}
model.params.list <- model.params.default
sim.params.list <- sim.params.default
sim.params.list[['B']] <- 1000

model.params.list[['K']] <- 1
model.params.list[['ICC.3']] <- NULL
model.params.list[['omega.3']] <- NULL
model.params.list[['numCovar.3']] <- 0
model.params.list[['R2.3']] <- NULL
model.params.list[['numCovar.2']] <- 0
model.params.list[['R2.2']] <- NULL

model.params.list[['J']] <- 60    

# so power isn't too high
model.params.list[['MDES']] <- rep(0.05, M)
model.params.list[['nbar']] <- 30
```

Constant effects

```{r}
d_m <- "d2.1_m2fc"
model.params.list[['omega.2']] <- NULL
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d2.1_m2fc_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d2.1_m2fc_power_plot)
```
\newpage
Fixed effects

```{r}
d_m <- "d2.1_m2ff"
model.params.list[['omega.2']] <- model.params.default[['omega.2']]
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d2.1_m2ff_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d2.1_m2ff_power_plot)
```
\newpage
Random effects

```{r}
d_m <- "d2.1_m2fr"
model.params.list[['omega.2']] <- model.params.default[['omega.2']]
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d2.1_m2fr_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d2.1_m2fr_power_plot)
```

\newpage
# d2.2 models

```{r}
model.params.list <- model.params.default
sim.params.list <- sim.params.default
sim.params.list[['B']] <- 1000

model.params.list[['K']] <- 1
model.params.list[['ICC.3']] <- NULL
model.params.list[['omega.3']] <- NULL
model.params.list[['numCovar.3']] <- 0
model.params.list[['R2.3']] <- NULL
model.params.list[['omega.2']] <- NULL

# params to help have a decent power
model.params.list[['ICC.2']] <- rep(0.1, M)
model.params.list[['J']] <- 60
model.params.list[['MDES']] <- rep(0.25, M)
```

```{r}
d_m <- "d2.2_m2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d2.2_m2rc_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d2.2_m2rc_power_plot)
```

\newpage
# d3.1 models

```{r}
model.params.list <- model.params.default
sim.params.list <- sim.params.default
sim.params.list[['B']] <- 100

# assumptions
model.params.list[['numCovar.3']] <- 0
model.params.list[['R2.3']] <- NULL
model.params.list[['numCovar.2']] <- 0
model.params.list[['R2.2']] <- NULL

# for a reasonable runtime and power
model.params.list[['nbar']] <- 20
model.params.list[['J']] <- 20
model.params.list[['K']] <- 20
```

```{r}
d_m <- "d3.1_m3rr2rr"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d3.1_m3rr2rr_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d3.1_m3rr2rr_power_plot)
```

\newpage
# d3.3 models

```{r}
model.params.list <- model.params.default
sim.params.list <- sim.params.default
sim.params.list[['B']] <- 1000

# assumptions
model.params.list[['omega.2']] <- NULL
model.params.list[['omega.3']] <- NULL

# for a reasonable power
model.params.list[['J']] <- 40
model.params.list[['K']] <- 20
model.params.list[['MDES']] <- rep(0.25, M)
model.params.list[['ICC.3']] <- rep(0.1, M)
model.params.list[['ICC.2']] <- rep(0.1, M)
```

```{r}
d_m <- "d3.3_m3rc2rc"
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d3.3_m3rc2rc_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d3.3_m3rc2rc_power_plot)
```

# d3.2 models

```{r}
model.params.list <- model.params.default
sim.params.list <- sim.params.default
sim.params.list[['B']] <- 1000

# assumptions
model.params.list[['numCovar.3']] <- 0
model.params.list[['R2.3']] <- NULL
model.params.list[['omega.2']] <- NULL
```

Constant effects

```{r}
d_m <- "d3.2_m3ff2rc"
model.params.list[['omega.3']] <- NULL
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d3.2_m3ff2rc_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d3.2_m3ff2rc_power_plot)
```

\newpage
Random effects

```{r}
# for reasonable power and runtime
model.params.list[['nbar']] <- 30
model.params.list[['J']] <- 15
model.params.list[['K']] <- 15
model.params.list[['MDES']] <- rep(0.25, M)

d_m <- "d3.2_m3rr2rc"
model.params.list[['omega.3']] <- model.params.default[['omega.3']]
params.file.base <- gen_params_file_base(model.params.list, sim.params.list, d_m)
d3.2_m3rr2rc_power_plot <- gen.power.results.plot(params.file.base, d_m)
print(d3.2_m3rr2rc_power_plot)
```